version: "3.8"

services:
    server:
          image: dekuyo/goblog-server:0.2
          secrets:
                  - goblog_database_url
          environment:
                  - DATABASE_URL_FILE=/run/secrets/goblog_database_url
                  - SWAGGER_HOST=http://37.46.128.188
                  - SWAGGER_BASE_PATH=/goblog/api/
                  - SWAGGER_PREFIX=/goblog/swagger/
          deploy:
                  restart_policy:
                          condition: on-failure
          ports:
                  - "9000:8000"
          extra_hosts:
                  - "host.docker.internal:host-gateway"
secrets:
        goblog_database_url:
                external: true